# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151218184805 on 2015-12-21 03:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='title',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together=set([('title', 'year')]),
        ),
    ]
