# -*- coding: utf-8 -*-
# Generated by Django 1.10.dev20151218184805 on 2015-12-21 06:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20151221_0358'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='moviecrew',
            unique_together=set([]),
        ),
    ]
